syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage
* Add syntax highlighting for but expressions
* Support match statement in anywhere where regular code can appear
=> Syntax highlighting for but

build.js, syntaxes/ballerina.tmLanguage
Avoid an invalid key named variables being set in the generated .tmLanguage file.
=> Remove variables entry from grammar after replacing them with values

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage
* Highlight elvis operator
* Highlight constrain types (stream<Customer>)
* Highlight 'forever' keyword
* Fix 'but' clauses to highlight parameter properly
=> Syntax highlighting improvements

prism/example.html, prism/prism-ballerina.js
Add ballerina syntax highlighting for prism.js
=> Add ballerina syntax highlighting for prism.js

build-monarch.js, package.json, syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage
Also update grammar to fix few syntax highlighting issues
=> Add the converter to convert from YAML-tml grammar to monarch grammar

build-monarch.js, syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Add syntax highlighting for object and record fields
=> Add syntax highlighting for object and record fields

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Add syntax highlighting for xml literals
=> Add syntax highlighting for xml literals

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Add syntax highlighting for symbolic string literals
=> Add syntax highlighting for symbolic string literals

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage
* Add new keywords
* Highlighting for new service syntax
* Fix function definition syntax highlighting
=> Update for new syntax

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage
Add syntax highlighting for type definitions with simple types and object defs
=> Update syntax highlighting for type definitions

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage
=> Add syntax highlighting for the new match statement

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage
$subject as these are no longer in the language
=> Remove endpoint and lengthof keywords

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage
> This PR will add highlighting of is keyword.
=> Add syntax highlighting for keyword 'is'

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage
=> Add syntax highlighting for checkpanic and extern

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage
Fixes ballerina-platform/ballerina-lang#15170
=> Fix bug where syntax highlighting breaks when last parameter is of a tuple type

build-monarch.js, syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
$title and Updated monarch grammar
=> Removed unused continuedType entry

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Update keywords for taint checking

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
=> Fix syntax highlighting for error destructuring and error match statement

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix syntax highlighting for all the following cases.
Also adds escaping for xml strings
Fixes ballerina-platform/ballerina-lang#17894
Fixes ballerina-platform/ballerina-lang#17489
Fixes ballerina-platform/ballerina-lang#15168
=> Fix issues in funciton signature for complex types

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
* keywords separated by | and & not highlighted properly
* Fix function pointer type return type breaking syntax highlighting
=> Fix following issues

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/19180
=> Fix new keywords for transactions - committed, aborted

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
$subject 
Fixes ballerina-platform/ballerina-lang#19376
=> Fix syntax highlighting for tuple type returns

prism/prism-ballerina.js, syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
This will add syntax highlighting for `let` keyword
=> Add syntax highlighting for let keyword

syntaxes/ballerina.YAML-tmLanguage
Updated the tm language grammar with latest lang changes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Syncup language changes

syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
$subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Generate tm xml and monarch

prism/extract-keywords.js, prism/prism-ballerina.js
> - Adds all the keywords from `ballerina-lang/compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/LexerTerminals`
> - Adds a script that can be used to add all the keywords
=> Add new keywords to prism

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
$subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Add class internal highliting

README.md
Update README.md with language file generation via scripts.
=> Update README with language file generation

prism/prism-ballerina.js, syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Update ballerina grammar with 'configurable' keyword.
=> Update with configurable keyword

package-lock.json, package.json, syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/147
=> Fix highlighting of class inner comments

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/83
=> Fix 'returns' highlighting of function typed fields within records

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/200
=> Fix doc highlighting inconsistency with multiple spaces

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/226
=> Fix isolated function highlighting

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/73
=> Fix highlighting issue with parentheses in param defaults

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/205
=> Fix template literal inconsistency

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/241
=> Fix highlight resource path segment params

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/232
=> Fix variable highlighting of class and record

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/238
=> Fix parameter descriptor highlighting

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/233
=> Fix final keyword inside class

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/228
=> Fix keyword highlighting inside match

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/240
=> Fix class highlighting inside service

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/270
=> Fix highlighting of function as a function param

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/266
=> Fix return with array of arrays highlighting

test-scripts/class.bal, test-scripts/function.bal, test-scripts/object.bal, test-scripts/service.bal, test-scripts/test.bal
Add scripts to test basic cases of highlighting.
=> Add test scripts

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/249
=> Fix annotation declaration highlighting

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/255
=> Fix type function highlighting

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/273
=> Fix base string template highlighting

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/242
=> Fix highlighting of function inside service object

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/269
=> Fix anonymous function highlighting

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/314
=> Fix highlighting after service class

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/342
=> Fix comment highlighting with functions

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage, test-scripts/function.bal
Fix https://github.com/ballerina-platform/plugin-vscode/issues/346
=> Fix worker returns highlighting

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage
Fix https://github.com/ballerina-platform/plugin-vscode/issues/350
=> Fix fork highlighting

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.monarch.json, syntaxes/ballerina.tmLanguage, test-scripts/class.bal, test-scripts/function.bal, test-scripts/object.bal
Fix https://github.com/wso2/ballerina-plugin-vscode/issues/81
Fix https://github.com/wso2/ballerina-plugin-vscode/issues/79
=> Fix mdDocs inside record descriptors

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage, test/resources/config/where.bal, test/resources/snapshots/where.bal.snap, test/unit-test.ts
> Resolves https://github.com/wso2/ballerina-plugin-vscode/issues/184
- Unit tests 
> Added unit tests
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
=> Fix nested query

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage, test/resources/config/json.bal, test/resources/snapshots/json.bal.snap, test/unit-test.ts
> Fix grammar issues
Resolves https://github.com/wso2/ballerina-plugin-vscode/issues/170, https://github.com/wso2/ballerina-plugin-vscode/issues/185.
=> Fix grammar issues

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
Fix the invalid regex that I reported in https://github.com/ballerina-platform/ballerina-grammar/issues/105
Fixes https://github.com/ballerina-platform/ballerina-grammar/issues/105
Removed the extra `*`. This is needed because `(\/({{identifier}}*)` results in …
=> Fix serviceName match regex error

syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage
This PR fixes three syntax errors detected by GitHub Linguist's grammar compiler:
* 'Repository[regex-unicode-property-key].Patterns[0].EndCaptures[patterns]' expected a map, got 'slice'
* 'Repository[unicode-property-escape].Patterns[0].EndCaptures[patterns]' expected a map, got 'slice'
* 'Repository[unicode-values].Patterns[0].EndCaptures[patterns]' expected a map, got 'slice'
These were introduced in https://github.com/ballerina-platform/ballerina-grammar/pull/108 and all due to indentation errors.
Fix grammar errors so GitHub can use the latest updates in this grammar for syntax highlighting.
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a …
=> Fix grammar syntax error caused by incorrect indentation

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/improvement.yml, .github/ISSUE_TEMPLATE/new-feature.yml, .github/ISSUE_TEMPLATE/task.yml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Add new issue template

package-lock.json, package.json, syntaxes/ballerina.YAML-tmLanguage, syntaxes/ballerina.tmLanguage, test/resources/config/natural.bal, test/resources/snapshots/natural.bal.snap, test/unit-test.ts
> This PR will add the syntax highlight support for naturals.
=> Add support for natural 

package-lock.json
> Fix package vulnerabilities.
> This PR fixes following vunerabilties.
> Results after fixing vunerabilties.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR …
=> Fix package vulnerabilities
